services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: recipe-api-dev:latest
    container_name: recipe-api-dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./requirements-dev.txt:/tmp/requirements-dev.txt
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
