services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: recipe-api-prod:latest
    container_name: recipe-api-prod
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.prod
    restart: unless-stopped
    command: >
      sh -c "python manage.py wait_for_db && \
             python manage.py migrate && \
             gunicorn --chdir app app.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: postgres:15
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file:
      - .env.prod
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_prod:
