services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: recipe-api-dev:latest
    container_name: recipe-api-dev
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - ./app:/app
      - ./requirements-dev.txt:/tmp/requirements-dev.txt
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - .env.dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev: