services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: recipe-api-prod:latest
    container_name: recipe-api-prod
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - .env.prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

volumes:
  postgres_data_prod: