services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: recipe-api-prod:latest
    container_name: recipe-api-prod
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PYTHONPATH: /app/app
      POSTGRES_USER: ${PROD_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PROD_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PROD_POSTGRES_DB}
      POSTGRES_HOST: ${PROD_POSTGRES_HOST}
      POSTGRES_PORT: ${PROD_POSTGRES_PORT}
      DJANGO_SETTINGS_MODULE: ${PROD_DJANGO_SETTINGS_MODULE}
      DEBUG: ${PROD_DEBUG}
      ALLOWED_HOSTS: ${PROD_ALLOWED_HOSTS}
      DB_WAIT_RETRIES: ${DB_WAIT_RETRIES:-30}
      DB_WAIT_DELAY: ${DB_WAIT_DELAY:-2}
    restart: unless-stopped
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: postgres:15
    container_name: recipe-api-db-prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PROD_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PROD_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PROD_POSTGRES_DB}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PROD_POSTGRES_USER:-postgres} -d ${PROD_POSTGRES_DB:-postgres}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_prod:
