name: CI Checks

on: [push, pull_request]

jobs:
  test-lint-dev:
    name: Test and Lint (Development)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Tests (Development)
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
          DEBUG: ${{ secrets.DEBUG }}
        run: |
          docker compose -f docker-compose.dev.yml run --rm \
          -e POSTGRES_USER \
          -e POSTGRES_PASSWORD \
          -e POSTGRES_DB \
          -e POSTGRES_HOST \
          -e POSTGRES_PORT \
          -e DJANGO_SETTINGS_MODULE \
          -e DEBUG \
          app python manage.py test

      - name: Run Lint (Development)
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
          DEBUG: ${{ secrets.DEBUG }}
        run: |
          docker compose -f docker-compose.dev.yml run --rm \
          -e POSTGRES_USER \
          -e POSTGRES_PASSWORD \
          -e POSTGRES_DB \
          -e POSTGRES_HOST \
          -e POSTGRES_PORT \
          -e DJANGO_SETTINGS_MODULE \
          -e DEBUG \
          app flake8 --config=/app/.flake8